#!/usr/bin/env bash
pushd "$HOME/.ssl" > /dev/null || return
./acme-cron
./acme-issue
service cron start > /dev/null
trap "service cron stop > /dev/null; exit" SIGINT SIGTERM
while true; do
  tail -F "$HOME/.acme.sh/acme.sh.log"
done
