#!/usr/bin/env bash
mkdir /tmp/acme.sh
pushd /tmp/acme.sh > /dev/null || return
git clone https://github.com/acmesh-official/acme.sh.git .
./acme.sh --install \
  --home "$HOME/.acme.sh" \
  --config-home "/mnt/acme.sh/data" \
  --cert-home "/mnt/acme.sh/certificates" \
  --accountemail "$LETS_ENCRYPT_MAIL"
popd > /dev/null || return
rm -rf /tmp/acme.sh
pushd "$HOME/.acme.sh" > /dev/null || return
./acme.sh --auto-upgrade
popd > /dev/null || return
